name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . -t fluffy41/discord-icloud-calendar:latest

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: fluffy41
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push fluffy41/discord-icloud-calendar:latest
