name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: fluffy41
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/discord-icloud-calendar:latest .
        echo "${DOCKER_ACCESS_TOKEN}" | docker login --username $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_USERNAME/discord-icloud-calendar:latest
